[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "secop-ophyd"
version = "0.0.1"
description = "An Interface between bluesky and SECoP, using ophyd and frappy-client"
[tool.setuptools.packages.find]
exclude = ["frappy*"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v"
asyncio_mode="auto"
norecursedirs="frappy"
